version: "3.7"

services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest # https://hub.docker.com/r/cloudflare/cloudflared
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
